// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: rec.proto

package rec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommendationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationRequest) Reset() {
	*x = RecommendationRequest{}
	mi := &file_rec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationRequest) ProtoMessage() {}

func (x *RecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationRequest.ProtoReflect.Descriptor instead.
func (*RecommendationRequest) Descriptor() ([]byte, []int) {
	return file_rec_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RecommendationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationResponse) Reset() {
	*x = RecommendationResponse{}
	mi := &file_rec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationResponse) ProtoMessage() {}

func (x *RecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationResponse.ProtoReflect.Descriptor instead.
func (*RecommendationResponse) Descriptor() ([]byte, []int) {
	return file_rec_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecommendationResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_rec_proto protoreflect.FileDescriptor

const file_rec_proto_rawDesc = "" +
	"\n" +
	"\trec.proto\x12\x03rec\"'\n" +
	"\x15RecommendationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x16RecommendationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids2\xb8\x01\n" +
	"\x15RecommendationService\x12P\n" +
	"\x15ProjectRecommendation\x12\x1a.rec.RecommendationRequest\x1a\x1b.rec.RecommendationResponse\x12M\n" +
	"\x12UserRecommendation\x12\x1a.rec.RecommendationRequest\x1a\x1b.rec.RecommendationResponseB\aZ\x05./recb\x06proto3"

var (
	file_rec_proto_rawDescOnce sync.Once
	file_rec_proto_rawDescData []byte
)

func file_rec_proto_rawDescGZIP() []byte {
	file_rec_proto_rawDescOnce.Do(func() {
		file_rec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rec_proto_rawDesc), len(file_rec_proto_rawDesc)))
	})
	return file_rec_proto_rawDescData
}

var file_rec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rec_proto_goTypes = []any{
	(*RecommendationRequest)(nil),  // 0: rec.RecommendationRequest
	(*RecommendationResponse)(nil), // 1: rec.RecommendationResponse
}
var file_rec_proto_depIdxs = []int32{
	0, // 0: rec.RecommendationService.ProjectRecommendation:input_type -> rec.RecommendationRequest
	0, // 1: rec.RecommendationService.UserRecommendation:input_type -> rec.RecommendationRequest
	1, // 2: rec.RecommendationService.ProjectRecommendation:output_type -> rec.RecommendationResponse
	1, // 3: rec.RecommendationService.UserRecommendation:output_type -> rec.RecommendationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rec_proto_init() }
func file_rec_proto_init() {
	if File_rec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rec_proto_rawDesc), len(file_rec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rec_proto_goTypes,
		DependencyIndexes: file_rec_proto_depIdxs,
		MessageInfos:      file_rec_proto_msgTypes,
	}.Build()
	File_rec_proto = out.File
	file_rec_proto_goTypes = nil
	file_rec_proto_depIdxs = nil
}
